name: build-image
on:
  workflow_dispatch: {}

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: chanwit
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone base model
        id: clone-base-model
        run: |
          git lfs install
          git clone https://huggingface.co/togethercomputer/GPT-NeoXT-Chat-Base-20B
          rm -rf GPT-NeoXT-Chat-Base-20B/.git
      - name: Build Push
        id: build-push
        run: |
          docker build ghcr.io/chanwit/flux-gpt/pytorch:3.10-1.13.1-116 .
          docker push  ghcr.io/chanwit/flux-gpt/pytorch:3.10-1.13.1-116
